apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content  
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: 5Gi
